import type { Novel } from "./types.js";

export function seedNovel(): Novel {
  return {
    id: "n1",
    title: "剑入星海",
    genre: "玄幻武侠",
    styleNotes: [
      "句子偏短，平均 14 字；少用长复句",
      "比喻克制，偏冷意象（雪、铁、灯、冻）",
      '对话不写"道""说"，少用"突然""忽然"',
      '沈砚（主角）：寡言，说"嗯"代替"是"，不主动开口',
    ],
    volumes: [
      { id: "vol1", title: "卷一 · 少年入江湖", order: 1 },
      { id: "vol2", title: "卷二 · 雪夜入城", order: 2 },
      { id: "vol3", title: "卷三 · 北望", order: 3 },
    ],
    chapters: [
      {
        id: "c38",
        volumeId: "vol1",
        num: 38,
        title: "北疆边境",
        status: "done",
        updatedAt: Date.now(),
        body: '北疆的雪下了三天，没有停的意思。沈砚把断剑收入鞘，回头看了一眼那座烽燧台。\n"走了？"卫衍站在他身后，手按在刀柄上，像是随时要拔。\n沈砚没答话，脚下踩着雪，往南走。',
      },
      {
        id: "c41",
        volumeId: "vol2",
        num: 41,
        title: "城门密谈",
        status: "done",
        updatedAt: Date.now(),
        body: "卷一第三十八章后，沈砚自北疆边境一路南下，雪未落足，已先至。\n他到的不是城。是城外三里的一座木桥。桥下河水未冻，桥上有一个老者。\n老者把断剑横在膝头，看他走近，看了很久，才说：「你父亲的剑，是这一截。」",
      },
      {
        id: "c42",
        volumeId: "vol2",
        num: 42,
        title: "雪夜城下",
        status: "writing",
        updatedAt: Date.now(),
        body: '雪线压着城墙，像一道压了三天三夜的眉。沈砚把斗篷往下扯，露出半张冻青的脸——城门口的灯笼在风里晃，像是要熄，又像是有人正在里头喘气。\n"外乡人？" 守门兵的矛尖斜下来，带着雪。\n沈砚没答话。他从怀里摸出半枚铜牌，铜牌缺角的地方还沾着旧血。\n守门兵的脸色一下变了。',
      },
      {
        id: "c43",
        volumeId: "vol2",
        num: 43,
        title: "城主之女",
        status: "draft",
        updatedAt: Date.now(),
        body: "雪夜城里第二盏灯亮起的时候，季元的女儿正在数她父亲今夜还会等到几个客人。",
      },
      {
        id: "c44",
        volumeId: "vol2",
        num: 44,
        title: "铜牌之约",
        status: "outline",
        updatedAt: Date.now(),
        body: "",
      },
      {
        id: "c60",
        volumeId: "vol3",
        num: 60,
        title: "铜牌归位",
        status: "outline",
        updatedAt: Date.now(),
        body: "",
      },
    ],
    terms: [
      {
        id: "t1",
        name: "半枚铜牌",
        kind: "物品 · 伏笔",
        body: "北疆军中信物，缺角者为叛逃之证。沈砚从父亲尸身上取下；另半枚在反派季元手中。",
        meta: "首次：第 17 章 · 计划回收：第 60 章前后",
        isForeshadow: true,
        plantedChapter: 17,
        recoverChapter: 60,
        status: "planted",
      },
      {
        id: "t2",
        name: "沈砚",
        kind: "人物 · 主角",
        body: "17 岁。瘦高，冻青脸，右手有冻疮。寡言、冷峻、重诺；对刀剑的反应快于对人。",
        meta: "出场 41 章",
      },
      {
        id: "t3",
        name: "季元",
        kind: "人物 · 反派",
        body: "雪夜城主，世袭。持完整另半枚铜牌。沈砚之父之死与他有关。",
        meta: "首次 第 38 章",
      },
      {
        id: "t4",
        name: "卫衍",
        kind: "人物 · 配角",
        body: "沈砚旧友，北疆斥候。第 29 章战亡，化为沈砚背负的心结。",
        meta: "出场 1–29 章",
      },
      {
        id: "t5",
        name: "白如霜",
        kind: "人物 · 配角",
        body: "雪夜城季元之女，表面顺从，暗中收集父亲罪证。与沈砚在第 43 章初遇。",
        meta: "首次 第 43 章",
      },
      {
        id: "t6",
        name: "雪夜城",
        kind: "地点",
        body: "北疆要塞城，季元世代驻守。城门设有铜牌验证，常年雪封。",
        meta: "卷二主要场景",
      },
      {
        id: "t7",
        name: "北疆",
        kind: "地点",
        body: "故事起点，边境苦寒之地。沈砚父亲在此守边，后被诬陷叛逃。",
      },
      {
        id: "t8",
        name: "断剑",
        kind: "物品 · 伏笔",
        body: "沈砚父亲遗剑，断为两截。沈砚持上半截；老者持下半截。两截合一暗示真相大白。",
        meta: "首次：第 41 章 · 计划回收：第 55 章",
        isForeshadow: true,
        plantedChapter: 41,
        recoverChapter: 55,
        status: "near",
      },
    ],
    characters: [
      {
        id: "ch1",
        name: "沈砚",
        role: "主角",
        description: "17 岁，瘦高，冻青脸，右手有冻疮。寡言、冷峻、重诺。",
        traits: ["寡言", "冷峻", "重诺", "剑术精湛"],
        firstChapter: 1,
        appearances: 42,
      },
      {
        id: "ch2",
        name: "季元",
        role: "反派",
        description: "雪夜城主，世袭。表面公正，暗中操控北疆。",
        traits: ["野心勃勃", "表里不一", "精于算计"],
        firstChapter: 38,
        appearances: 8,
      },
      {
        id: "ch3",
        name: "卫衍",
        role: "配角",
        description: "沈砚旧友，北疆斥候。忠勇，第 29 章战亡。",
        traits: ["忠勇", "直率", "重义"],
        firstChapter: 1,
        appearances: 28,
      },
      {
        id: "ch4",
        name: "白如霜",
        role: "配角",
        description: "季元之女，暗中反抗父亲。",
        traits: ["聪慧", "隐忍", "善谋"],
        firstChapter: 43,
        appearances: 1,
      },
    ],
    revisions: [
      {
        id: "r1",
        chapterId: "c42",
        timestamp: Date.now() - 3600000,
        type: "auto",
        label: "自动保存",
        snapshot: "雪线压着城墙，像一道压了三天三夜的眉。",
        milestone: false,
      },
      {
        id: "r2",
        chapterId: "c42",
        timestamp: Date.now() - 7200000,
        type: "ai",
        label: "AI 续写：城门交涉",
        snapshot: "雪线压着城墙。沈砚走近城门，守门兵的矛尖斜下来。",
        milestone: true,
      },
    ],
    writingLog: [
      { date: new Date(Date.now() - 86400000 * 2).toISOString().slice(0, 10), wordsAdded: 1800 },
      { date: new Date(Date.now() - 86400000).toISOString().slice(0, 10), wordsAdded: 2340 },
    ],
    todos: [],
  };
}
